### ISSUE TITLE
python version 

### ISSUE THREAD

**Issue by EH-HU** [dendenxu/fast-gaussian-rasterization#3]
I was wondering if it's not available in Python version 3.8.

**Comment by dendenxu** [comment]
I don't recall using any special features from 3.9 or newer so theoretically it should also work on 3.8.
I listed 3.9 in `pyproject.toml` since I only tested on 3.9 or newer versions of Python.

I'll test on more python-pytorch version combinations in the future, but in the moment I don't have a readily available Python 3.8 environment at hand.
Maybe you could clone the repo and manually update `pyproject.toml`'s Python requirement to 3.8 and check whether there's any issue? If all goes well, I can release a version that also marks Python 3.8 as supported.

**Comment by dendenxu** [comment]
ps: another way to install the package without installing all dependencies: `pip install fast_gauss --no-build-isolation --no-deps`

**Comment by EH-HU** [comment]
Thank you for your quick response.
Do you know why the rendering time was longer when using that module?

**Comment by dendenxu** [comment]
Could be due to multiple factors, for example, the number of points (the lower the faster compared to the vanilla) and the target resolution (the higher the faster compared to the vanilla renderer).
Another thing to note is that the speedup is the most visible when you're rendering to a screen, compared to maybe saving the rendered image to disk.

**Comment by EH-HU** [comment]
Thank you for your response.
